name: Run linter
on:
  push:
jobs:
  Run-unit-tests-and-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Composer install
        run: composer install

      - name: Run linter
        run: make lint